# site settings
title: 低利宅生 DZ Channel
subtitle: Blog
email: dzchannel@davispcc.com
description: 低利宅生是一個分享ACGN的非主流話題、七年級懷舊話題的Podcast節目。
baseurl: /dclakelock # the subpath of your site, e.g. /blog
url: https://davispcc.com/ # the base hostname & protocol for your site 

# homepage tiles
tiles-source: posts # accepts "posts" or "pages"
tiles-count: 4

# social settings
instagram_url: https://www.instagram.com/dzchannel2020/
twitter_url: https://twitter.com/dzchannel2020

# podcast platforms
spotify_url: https://open.spotify.com/show/41emKt8hoCb0x71DhddyjD
applepodcasts_url: https://podcasts.apple.com/podcast/id1515231624
firstory_url: https://dzchannel.firstory.io/
googlepodcasts_url:


# build settings
markdown: kramdown

sass:
  style: compressed
